import {test, expect} from '@playwright/test';

test('直接注册、自带 Key、明确选择 PDF 模型和删除密钥', async ({page}) => {
  await page.goto('/');
  await page.getByRole('button', {name: '注册账号', exact: true}).click();
  await expect(page.getByLabel('邀请码', {exact: true})).toHaveCount(0);
  await page.getByLabel('用户名', {exact: true}).fill('provider_' + Date.now());
  await page.getByLabel('密码（12–128 位）', {exact: true}).fill('synthetic-web-passphrase-2026');
  await page.getByRole('button', {name: '注册并开始使用'}).click();
  await page.getByRole('button', {name: 'PDF 导入'}).click();
  await expect(page.getByLabel('使用我的模型整理简历')).toBeDisabled();
  await expect(page.getByText('仅提取 PDF 文字，由你手动整理，不调用外部模型。')).toBeVisible();
  await page.getByRole('button', {name: '配置我的模型 API'}).click();
  await page.getByLabel('模型 API Key', {exact: true}).fill('synthetic-personal-browser-key');
  await page.getByRole('button', {name: '保存模型设置', exact: true}).click();
  await expect(page.getByText('模型设置已保存，可以测试连接。')).toBeVisible();
  await expect(page.getByLabel('模型 API Key', {exact: true})).toHaveValue('');
  await page.getByRole('button', {name: '测试已保存的连接'}).click();
  await expect(page.getByText('连接成功，模型已返回有效的结构化结果。')).toBeVisible();
  expect(JSON.stringify(await (await page.request.get('/v1/model-settings')).json())).not.toContain('synthetic-personal-browser-key');
  await page.screenshot({path:'artifacts/screenshots/web/personal-models.png', fullPage:true, animations:'disabled'});
  await page.getByRole('button', {name: 'PDF 导入'}).click();
  await expect(page.getByLabel('使用我的模型整理简历')).toBeEnabled();
  await expect(page.getByLabel('使用我的模型整理简历')).not.toBeChecked();
  await page.getByLabel('使用我的模型整理简历').check();
  await expect(page.getByText(/将提取的文字发送至 https:\/\/api.deepseek.com\/anthropic/)).toBeVisible();
  await page.getByRole('button', {name: '更换模型设置'}).click();
  page.once('dialog', d => d.accept());
  await page.getByRole('button', {name:'删除模型 Key', exact:true}).click();
  await expect(page.getByText('模型 Key 已删除。')).toBeVisible();
  await expect(page.getByRole('button', {name:'测试已保存的连接'})).toBeDisabled();
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([]);
});
