import {configureModel} from './helpers';
import { test, expect, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { mkdirSync } from 'node:fs';
const password = 'synthetic-web-passphrase-2026';
async function login(page: Page) {
  await page.goto('/'); await page.getByLabel('用户名', {exact: true}).fill('administrator'); await page.getByLabel('密码（12–128 位）', {exact: true}).fill(password); await page.getByRole('button', {name: '登录工作台'}).click(); await expect(page.getByRole('heading', {name: '我的简历.'})).toBeVisible();
}
test.beforeAll(() => {
  mkdirSync('test-results/web', {recursive: true}); mkdirSync('artifacts/screenshots/web', {recursive: true});
  execFileSync('backend/.venv/bin/python', ['-c', "import sys;sys.path[:0]=['backend','backend/tests'];from test_imports import pdf;open('test-results/web/resume.pdf','wb').write(pdf())"]);
});
test('直接注册、网页编辑与 API Key 读取已确认简历', async ({page}) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await login(page);
  await page.getByRole('button', {name: '退出登录', exact: true}).click();
  await page.getByRole('button', {name: '注册账号', exact: true}).click();
  await page.getByLabel('用户名', {exact: true}).fill('student_' + Date.now());
  await page.getByLabel('密码（12–128 位）', {exact: true}).fill(password);
  await page.getByRole('button', {name: '注册并开始使用'}).click();
  await expect(page.getByRole('button', {name: '管理工作台'})).toHaveCount(0);
  await page.getByRole('button', {name: '新建简历'}).click();
  await page.getByLabel('简历名称', {exact: true}).fill('测试开发方向');
  await page.getByLabel('姓名', {exact: true}).fill('合成测试同学');
  await page.getByLabel('电子邮箱', {exact: true}).fill('synthetic@example.com');
  await page.getByRole('button', {name: '教育经历'}).click();
  await page.getByRole('button', {name: '添加教育经历'}).click();
  await page.getByLabel('学校名称', {exact: true}).fill('合成示例大学');
  await page.getByLabel('就读学历').selectOption('master');
  await page.getByLabel('预计获得学位', {exact: true}).fill('工学硕士');
  await page.getByRole('button', {name: '保存修改', exact: true}).click();
  await expect(page.getByText('已保存到你的账号，插件同步后即可使用。')).toBeVisible();
  await page.getByRole('button', {name: '← 我的简历', exact: true}).click();
  await expect(page.getByRole('heading', {name: '测试开发方向', exact: true})).toBeVisible();
  await page.screenshot({path: 'artifacts/screenshots/web/resumes-desktop.png', fullPage: true});
  await page.getByRole('button', {name: '连接插件'}).click();
  await page.getByLabel('密钥名称', {exact: true}).fill('浏览器测试插件');
  await page.getByRole('button', {name: '创建密钥', exact: true}).click();
  const key = await page.getByRole('textbox', {name: '你的 API Key', exact: true}).inputValue();
  await page.getByRole('button', {name: '已保存，关闭'}).click();
  const response = await page.request.get('/v1/resumes', {headers: {Authorization: 'Bearer ' + key}});
  expect(response.status()).toBe(200); const listing = await response.json(); expect(listing.resumes[0].name).toBe('测试开发方向');
  const detail = await (await page.request.get('/v1/resumes/' + listing.resumes[0].id, {headers: {Authorization: 'Bearer ' + key}})).json();
  expect(detail.profile.basic.full_name).toBe('合成测试同学'); expect(detail.profile.education[0].degree).toBeNull();
  await page.reload(); await expect(page.getByRole('heading', {name: '我的简历.'})).toBeVisible();
  const cookies = await page.context().cookies(); expect(cookies.find(c => c.name === 'resume_session')?.httpOnly).toBe(true);
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([]); expect(errors).toEqual([]);
});
test('PDF 核对保存、历史修订与冲突保留编辑内容', async ({page}) => {
  await login(page); await configureModel(page.request); await page.getByRole('button', {name: 'PDF 导入'}).click();
  await page.getByLabel('使用我的模型整理简历').check();
  await expect(page.getByRole('button', {name: '选择 PDF 文件', exact: true})).toBeEnabled();
  const chooserEvent = page.waitForEvent('filechooser');
  await page.getByRole('button', {name: '选择 PDF 文件', exact: true}).click();
  const chooser = await chooserEvent; await chooser.setFiles('test-results/web/resume.pdf');
  await expect(page.getByRole('button', {name: '核对并整理'}).first()).toBeVisible({timeout: 15000});
  await page.getByRole('button', {name: '核对并整理'}).first().click();
  await expect(page.getByLabel('姓名', {exact: true})).toHaveValue('Example Student');
  await expect(page.getByRole('button', {name: '确认并保存简历', exact: true})).toBeDisabled();
  await page.getByLabel('姓名', {exact: true}).fill('已核对的合成姓名');
  await page.getByLabel('我已核对简历内容，确认保存当前资料').check();
  await page.getByRole('button', {name: '确认并保存简历', exact: true}).click();
  await expect(page.getByText('已保存到「我的简历」，可以创建 API Key 并连接插件。')).toBeVisible();
  await page.getByRole('complementary').getByRole('button', {name: '我的简历'}).click();
  await page.getByRole('button', {name: '编辑简历'}).first().click();
  await page.getByLabel('姓名', {exact: true}).fill('在旧页编辑的名字');
  const me = await (await page.request.get('/v1/me')).json(); const list = await (await page.request.get('/v1/resumes')).json();
  const current = await (await page.request.get('/v1/resumes/' + list.resumes[0].id)).json();
  current.profile.basic.full_name = '另一页先保存的名字';
  expect((await page.request.patch('/v1/resumes/' + current.id, {headers: {'X-CSRF-Token': me.csrf_token}, data: {expected_revision: current.revision, name: current.name, profile: current.profile}})).status()).toBe(200);
  await page.getByRole('button', {name: '保存修改', exact: true}).click();
  await expect(page.getByRole('alert')).toContainText('其他页面更新');
  await expect(page.getByLabel('姓名', {exact: true})).toHaveValue('在旧页编辑的名字');
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', {name: '← 我的简历', exact: true}).click();
  await page.getByRole('button', {name: '编辑简历'}).first().click();
  await page.getByRole('button', {name: '查看历史修订'}).click();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', {name: '恢复', exact: true}).first().click();
  await expect(page.getByLabel('姓名', {exact: true})).toHaveValue('已核对的合成姓名');
});
test('移动端工作台与静态资源边界', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844}); await login(page);
  await page.getByRole('button', {name: '新建简历'}).click(); await page.getByRole('button', {name: '教育经历'}).click();
  await page.getByRole('button', {name: '添加教育经历'}).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path: 'artifacts/screenshots/web/editor-mobile.png', fullPage: true});
  const root = await page.request.get('/'); expect(root.headers()['content-security-policy']).toContain("frame-ancestors 'none'");
  expect((await page.request.get('/.runtime/config.json')).status()).toBe(404);
  expect((await page.request.get('/assets/..%2f..%2fapp%2fconfig.py')).status()).toBe(404);
});
