// Original controlled React fixture modeled on inspected public Phoenix DOM.
import React,{useState,useLayoutEffect,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {createPortal} from 'react-dom';
let oracle={ready:false,values:{},adds:0};window.fixtureOracle=()=>JSON.parse(JSON.stringify(oracle));
const css=document.createElement('style');css.textContent=`.section{border:1px solid #ddd;padding:12px;margin:8px}.ux-standard-form{border:1px dashed #999;padding:10px;margin:6px}.form-item{display:flex;gap:10px;margin:12px;align-items:start}.form-item__title{width:130px}.phoenix-select{border:1px solid #888;width:220px;padding:8px;cursor:pointer;position:relative}.phoenix-select input{width:160px}.phoenix-select__tipWrapper{display:block}.common-unmodeled-layer__layerContent{position:fixed;top:35px;right:25px;background:white;border:1px solid #777;z-index:100;width:290px;padding:12px}.phoenix-selectList__listItem{padding:8px;cursor:pointer}.phoenix-calendar td{padding:10px;cursor:pointer}.phoenix-calendar a{display:inline-block;min-width:25px;padding:5px;cursor:pointer}.phoenix-radio-group{display:flex}.phoenix-radio{padding:8px;cursor:pointer}.phoenix-radio--checked{background:#adf}.phoenix-calendar-selected-day,.phoenix-calendar-month-panel-selected-cell{background:#adf}.phoenix-selectList__listItem--disabled{opacity:.4}textarea{width:360px;height:60px}`;document.head.append(css);
function Select({value='',change,choices,date=false,month=false,reject=false}){
 const [open,setOpen]=useState(false),[closing,setClosing]=useState(false),[query,setQuery]=useState('');const root=useRef(),popup=useRef();
 const [year,setYear]=useState(2026),[mm,setMonth]=useState(9),[mode,setMode]=useState(month?'month':'date');
 useEffect(()=>{const fn=e=>{if(!root.current?.contains(e.target)&&!popup.current?.contains(e.target))setOpen(false);};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn);},[]);
 const commit=v=>{change(v);if(reject)setTimeout(()=>change(''),60);setOpen(false);setClosing(true);setTimeout(()=>setClosing(false),180);setQuery('');};
 const openPanel=()=>{setYear(Number(value.slice(0,4))||2026);setMonth(Number(value.slice(5,7))||9);setMode(month?'month':'date');setOpen(true);};
 const prefix=mode==='year'?'phoenix-calendar-year-panel':mode==='month'?'phoenix-calendar-month-panel':'phoenix-calendar';
 const yearBase=Math.floor(year/10)*10;
 const cells=mode==='year'?Array.from({length:10},(_,i)=>yearBase+i):mode==='month'?Array.from({length:12},(_,i)=>i+1):Array.from({length:new Date(year,mm,0).getDate()},(_,i)=>i+1);
 const iso=n=>`${year}-${String(mode==='month'?n:mm).padStart(2,'0')}${mode==='date'?`-${String(n).padStart(2,'0')}`:''}`;
 return <><div ref={root} className={`phoenix-select ${open?'phoenix-select--active':''}`} onClick={openPanel}>{date&&<svg width="12" height="12"><path id="fixture_field_date_time_picker"/></svg>}<input value={query} onChange={e=>setQuery(e.target.value)}/>{value&&<span className="phoenix-select__tipWrapper phoenix-select__tipWrapper--visible"><span className="phoenix-select__tipEle">{value}</span></span>}</div>{(open||closing)&&createPortal(<div className="common-unmodeled-layer__layerContent" ref={popup}>{!date?<div className="phoenix-selectList"><div className="phoenix-selectList__searchWrapper"><input placeholder="搜索" value={query} onFocus={e=>{e.currentTarget.value=query;}} onChange={e=>setQuery(e.target.value)}/></div><ul>{choices.filter(c=>c.includes(query)).map(c=><li key={c} className={`phoenix-selectList__listItem ${c==='禁用'?'phoenix-selectList__listItem--disabled':''}`} onClick={()=>c!=='禁用'&&commit(c)}><div className="phoenix-selectList__singleLabel">{c}</div></li>)}</ul></div>:<div className="phoenix-calendar"><div className={mode==='date'?'phoenix-calendar-date-panel':prefix}><div className={`${prefix}-header`}><a className={`${prefix}-${mode==='year'?'prev-decade-btn':'prev-year-btn'}`} onClick={()=>setYear(y=>y-(mode==='year'?10:1))}>‹</a><a className={`${prefix}-${mode==='year'?'decade-select':'year-select'}`} onClick={()=>setMode('year')}>{mode==='year'?`${yearBase}-${yearBase+9}`:`${year}年`}</a>{mode==='date'&&<a className="phoenix-calendar-month-select" onClick={()=>setMode('month')}>{mm}月</a>}<a className={`${prefix}-${mode==='year'?'next-decade-btn':'next-year-btn'}`} onClick={()=>setYear(y=>y+(mode==='year'?10:1))}>›</a></div><table><tbody>{Array.from({length:Math.ceil(cells.length/4)},(_,i)=><tr key={i}>{cells.slice(i*4,i*4+4).map(n=><td key={n} className={`${prefix}-cell ${iso(n)===value?mode==='date'?'phoenix-calendar-selected-day':`${prefix}-selected-cell`:''}`} onClick={()=>{if(mode==='year'){setYear(n);setMode(month?'month':'date');}else if(mode==='month'&&!month){setMonth(n);setMode('date');}else commit(iso(n));}}>{n}{mode==='month'?'月':''}</td>)}</tr>)}</tbody></table></div></div>}</div>,document.body)}</>;
}
function Area({value=[],change,reject=false,constant=false,single=false}){
 const values=Array.isArray(value)?value:value?[value]:[];
 const [open,setOpen]=useState(false),[draft,setDraft]=useState([]),[query,setQuery]=useState(''),[settled,setSettled]=useState('');const root=useRef(),popup=useRef();
 useEffect(()=>{const t=setTimeout(()=>setSettled(query),100);return()=>clearTimeout(t);},[query]);
 useEffect(()=>{const fn=e=>{if(!root.current?.contains(e.target)&&!popup.current?.contains(e.target))setOpen(false);};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn);},[]);
 return <><div ref={root} className={`phoenix-select ${single?'':'phoenix-select--multi'} ${open?'phoenix-select--active':''}`} onClick={()=>{setDraft([...values]);setOpen(true);}}>{values.length===0&&<input readOnly value=""/>}{single?<span className="phoenix-select__tipWrapper--visible"><span className="phoenix-select__tipEle">{values[0]}</span></span>:values.map(v=><span className="phoenix-select__tag" key={v}>{v}</span>)}</div>{open&&createPortal(<div ref={popup} className="common-unmodeled-layer__layerContent"><div className={constant?"constant-main-selector-container":"area-selector-container"}><div className={constant?"content-search":"area-search-input"}><input placeholder="搜索" value={query} onFocus={e=>{e.currentTarget.value=query;}} onChange={e=>setQuery(e.target.value)}/></div><div className="area-data-container">{(constant?['银行','培训生类']:['杭州市','上海市','南京市']).filter(v=>!settled||v.includes(settled)).map(v=><div className={constant?"list-item-container":"area-item-container"} key={v}><div className="area-item-name"><span className="icon-container visible" style={{display:'inline-block',width:24,height:24,border:'1px solid #aaa'}} onClick={()=>setDraft(d=>d.includes(v)?d.filter(x=>x!==v):single?[v]:[...d,v])}><svg width="16" height="16" className={draft.includes(v)?'area-icon-CheckboxChecked':'area-icon-CheckboxUnchecked'}/></span><span className={constant?"item-text-label no-hover":"area-text-label no-hover"}>{v}</span></div><div className="area-item-path">测试省</div></div>)}</div><div className="select-data-container">{draft.map(v=><div key={v}>{v}</div>)}</div><div className="phoenix-button" onClick={()=>{if(!reject)change(single?draft[0]:draft);setOpen(false);}}>确定</div></div></div>,document.body)}</>;
}
function Autocomplete({value='',change}) {
 const [query,setQuery]=useState(value),[focused,setFocused]=useState(false),[settled,setSettled]=useState('');
 useEffect(()=>{const t=setTimeout(()=>setSettled(query),100);return()=>clearTimeout(t);},[query]);
 const choices=['测试学校0','测试学校1','测试学校2'].filter(c=>settled&&c.includes(settled));
 return <><div className="phoenix-auto-complete-container"><input value={query} onFocus={()=>setFocused(true)} onChange={e=>setQuery(e.target.value)} onBlur={()=>{setFocused(false);setQuery(value);}}/></div>{focused&&choices.length>0&&createPortal(<div className="common-unmodeled-layer__layerContent"><ul>{choices.map(c=><li key={c} className="phoenix-selectList__listItem" onMouseDown={e=>e.preventDefault()} onClick={()=>{change(c);setQuery(c);setFocused(false);}}><div className="phoenix-selectList__singleLabel">{c}</div></li>)}</ul></div>,document.body)}</>;
}
const schemas={'个人信息':[['职业目录','constant'],['行业目录','constantMulti'],['期望城市','area'],['拒绝城市','rejectArea'],['姓名','text'],['性别','radio'],['出生日期','date'],['拒绝日期','rejectDate'],['验证错误','error']],'教育经历':[['学校名称','autocomplete'],['专业名称','text'],['学历','select'],['开始时间','month'],['结束时间','month']],'工作经历':[['公司名称','text'],['职位名称','text'],['工作职责','long']]};
function App(){
 const [data,setData]=useState(Object.fromEntries(Object.keys(schemas).map(s=>[s,[{}]])));
 useLayoutEffect(()=>{oracle.ready=true;oracle.values=data;},[data]);
 const put=(section,i,key,val)=>setData(d=>({...d,[section]:d[section].map((r,n)=>n===i?{...r,[key]:val}:r)}));
 return <><div className="common-unmodeled-layer-hidden" style={{position:'absolute',left:-1000,opacity:0}}><div className="common-unmodeled-layer__layerContent"><li className="phoenix-selectList__listItem">错误的残留选项</li></div></div>{Object.entries(schemas).map(([section,fields])=>{const id=`fixture_${section}_DefaultForm`;return <div className="section" key={section}><div id={id}>{section}</div><div>{data[section].map((row,i)=><div key={i}><div className="ux-standard-form"><div className="form" id={id}><div className="form-part">{fields.map(([label,type])=><div className="form-item form-item--phoenix" key={label}><div className="form-item__title"><a className="form-item__required">*</a><label className="form-item__text">{label}</label></div><div className="form-item__control">{type==='autocomplete'?<Autocomplete value={row[label]} change={v=>put(section,i,label,v)}/>:['area','rejectArea','constant','constantMulti'].includes(type)?<Area constant={type.startsWith('constant')} single={type==='constant'} value={row[label]} change={v=>put(section,i,label,v)} reject={type==='rejectArea'}/>:type==='radio'?<div className="phoenix-radio-group">{['男','女'].map(v=><div key={v} className={`phoenix-radio ${row[label]===v?'phoenix-radio--checked':''}`} onClick={()=>put(section,i,label,v)}><span className="phoenix-radio__radio-text">{v}</span></div>)}</div>:['select','date','month','rejectDate'].includes(type)?<Select value={row[label]} change={v=>put(section,i,label,v)} choices={['高中','本科','硕士研究生','禁用']} date={type!=='select'} month={type==='month'} reject={type==='rejectDate'}/>:type==='long'?<textarea value={row[label]||''} onChange={e=>put(section,i,label,e.target.value)}/>:<input value={row[label]||''} onChange={e=>put(section,i,label,e.target.value)}/>} {type==='error'&&<div className="form-item__error">必填信息不完整</div>}</div></div>)}</div></div></div></div>)}{section!=='个人信息'&&<div id={`${id}_addButton`} onClick={()=>{oracle.adds++;setData(d=>({...d,[section]:[...d[section],{}]}));}}><span>添加{section}</span></div>}</div></div>})}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
