import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {JournalEntrySchema,journalStatuses,journalStats,type JournalEntry} from '../domain/journal';
import {action,downloadFile,inExtension,openOptions,openModelSettings,STATE_KEY} from '../shared/client';
import {Brand,Modal,Notice} from '../shared/ui';
import '../shared/style.css';
type JournalState={entries:JournalEntry[];revision:number};
const today=()=>new Date().toLocaleDateString('sv-SE');
function App(){
  const [state,setState]=useState<JournalState>({entries:[],revision:0}),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<JournalEntry|null>(null),[base,setBase]=useState(0),[remove,setRemove]=useState<JournalEntry|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(open=false){try{const s=await action<JournalState>('JOURNAL_LIST');setState(s);if(open&&location.hash){const e=s.entries.find(e=>e.id===decodeURIComponent(location.hash.slice(1)));if(e){setEditing(e);setBase(s.revision);}}}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load(true);if(!inExtension)return;const changed=(changes:Record<string,chrome.storage.StorageChange>,area:string)=>{if(area==='local'&&changes[STATE_KEY])void load();};chrome.storage.onChanged.addListener(changed);return()=>chrome.storage.onChanged.removeListener(changed);},[]);
  const entries=state.entries.filter(e=>(filter==='all'||e.status===filter)&&`${e.company} ${e.role} ${e.notes}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.createdAt-a.createdAt),stats=journalStats(state.entries);
  function edit(entry:JournalEntry){setEditing({...entry});setBase(state.revision);setError('');}
  async function save(){if(!editing)return;const parsed=JournalEntrySchema.safeParse(editing);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);try{setState(await action('JOURNAL_SAVE',{entry:parsed.data,expectedRevision:base}));setEditing(null);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function del(){if(!remove)return;setBusy(true);try{setState(await action('JOURNAL_DELETE',{id:remove.id,expectedRevision:state.revision}));setRemove(null);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function csv(){const cell=(v:string)=>'"'+(/^[\s=+@\-]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"';const rows=[['公司','岗位','进展','记录日期','网址','备注'],...entries.map(e=>[e.company,e.role,journalStatuses[e.status],e.appliedDate??'',e.url,e.notes])];downloadFile('投递记录.csv','\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv');}
  return <div className="journal-workspace"><header className="journal-header"><Brand/><nav><button onClick={openOptions}>我的简历</button><button onClick={openModelSettings}>模型设置</button></nav></header><main><div className="journal-title"><div><span className="eyebrow">APPLICATION JOURNAL</span><h1>投递记录<span className="title-dot">.</span></h1><p>把每一次申请和后续进展留在这里。</p></div><button className="primary" onClick={()=>edit({id:crypto.randomUUID(),company:'',role:'',url:'https://',status:'recorded',appliedDate:today(),notes:'',createdAt:Date.now(),updatedAt:Date.now(),evidence:'manual',sessionKey:null})}>＋ 新建记录</button></div>
    <section className="stat-grid">{[[stats.total,'记录岗位'],[stats.companies,'家公司'],[stats.interviews,'面试中'],[stats.offers,'已获 Offer']].map(([value,label])=><div className="stat-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <Notice>在网页打开插件并扫描后，自动留下检测到的提交记录。这里保存页面信息，实际投递结果以招聘网站为准；有遗漏时可以手动添加。</Notice>
    {error&&!editing&&<Notice error>{error}</Notice>}<div className="journal-toolbar"><input aria-label="搜索投递记录" placeholder="搜索公司、岗位或备注" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="筛选投递状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(journalStatuses).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><button onClick={csv}>导出 CSV</button><button onClick={()=>downloadFile('投递记录.json',{format:'resume-application-journal',version:1,entries:state.entries})}>导出 JSON</button></div>
    <div className="journal-table"><table><thead><tr><th>公司与岗位</th><th>状态</th><th>记录日期</th><th>网址</th><th>操作</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td><strong>{e.company||'未识别公司'}</strong><p>{e.role||'未识别岗位'}</p><small>{e.evidence==='submit_detected'?'检测到提交动作':e.evidence==='success_detected'?'检测到页面成功提示':'手动记录'}</small></td><td><span className="journal-status">{journalStatuses[e.status]}</span></td><td>{e.appliedDate??new Date(e.createdAt).toLocaleDateString('zh-CN')}<small className="block">记录于 {new Date(e.createdAt).toLocaleDateString('zh-CN')}</small></td><td><a href={e.url} target="_blank" rel="noreferrer noopener">打开投递页面 ↗</a></td><td><button onClick={()=>edit(e)}>编辑</button><button className="danger-text" onClick={()=>setRemove(e)}>删除</button></td></tr>)}</tbody></table>{entries.length===0&&<div className="journal-empty">还没有符合条件的记录。完成申请后，可以从插件侧栏带入页面信息。</div>}</div>
    <p className="subtle">共 {state.entries.length} / 1000 条，本地保存。完整资料备份包含投递记录；记录直接计入统计，无需逐条确认。</p>
  </main>{editing&&<Modal title="编辑投递记录" onClose={()=>setEditing(null)}><div className="form-grid"><label className="form-field"><span>公司</span><input value={editing.company} maxLength={160} onChange={e=>setEditing({...editing,company:e.target.value})}/></label><label className="form-field"><span>岗位</span><input value={editing.role} maxLength={200} onChange={e=>setEditing({...editing,role:e.target.value})}/></label><label className="form-field"><span>跟进状态</span><select aria-label="跟进状态" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as JournalEntry['status'],appliedDate:editing.appliedDate??today()})}>{Object.entries(journalStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="form-field"><span>记录日期</span><input type="date" value={editing.appliedDate??''} onChange={e=>setEditing({...editing,appliedDate:e.target.value||null})}/></label><label className="form-field span-2"><span>投递网址</span><input type="url" value={editing.url} maxLength={3000} onChange={e=>setEditing({...editing,url:e.target.value})}/></label><label className="form-field span-2"><span>备注</span><textarea value={editing.notes} maxLength={2000} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label></div>{error&&<Notice error>{error}</Notice>}{base!==state.revision&&<Notice error>其他窗口或网页新增了记录。请取消后重新打开这条记录，避免覆盖更新。</Notice>}<div className="modal-actions"><button onClick={()=>setEditing(null)}>取消</button><button className="primary" disabled={busy||base!==state.revision} onClick={save}>保存记录</button></div></Modal>}
  {remove&&<Modal title="删除投递记录？" onClose={()=>setRemove(null)}><p>删除 {remove.company||'未识别公司'} · {remove.role||'未识别岗位'}，已有备份文件保留。</p><div className="modal-actions"><button onClick={()=>setRemove(null)}>取消</button><button disabled={busy} onClick={del}>确认删除记录</button></div></Modal>}</div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
