import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {demoProfile,emptyProfile,newRecord,type Profile} from '../domain/profile';
import {parseBackup,bytes,type Backup,type EditorExport} from '../domain/state';
import {exportMarkdown,type MarkdownResult} from '../domain/markdown';
import {AI_PROMPT,EMPTY_MARKDOWN} from '../domain/markdown-template';
import {navigation,ProfileFields,importDiff,describeImport,type Tab} from '../shared/profile-editor';
import {action,downloadFile,inExtension,openJournal} from '../shared/client';
import {Brand,Modal,Notice} from '../shared/ui';
import {useEditor} from './use-editor';
import {ModelSettings} from './model-settings';
import '../shared/style.css';

type Page=Tab|'import'|'backup'|'models';
const extra=[['import','从 AI 导入'],['backup','备份与恢复'],['models','模型设置']] as const;
function App(){
  const e=useEditor(),[tab,setTab]=useState<Page>(location.hash==='#models'?'models':'basic');
  const [result,setResult]=useState<{data:MarkdownResult;version:number}|null>(null),[parsing,setParsing]=useState(false),[ack,setAck]=useState(false),[message,setMessage]=useState('');
  const [pendingDraft,setPendingDraft]=useState<EditorExport|null>(null);
  const [pending,setPending]=useState<Profile|null>(null),[backup,setBackup]=useState<Backup|null>(null),[snapshot,setSnapshot]=useState<'current'|'previous'>('current');
  const [versionDialog,setVersionDialog]=useState<'new'|'copy'|'rename'|'delete'|null>(null),[versionName,setVersionName]=useState(''),[versionBusy,setVersionBusy]=useState(false);
  const [confirm,setConfirm]=useState<'clear'|'restore'|'discard'|'draft'|null>(null);
  const parser=useRef<Worker|null>(null),input=useRef<HTMLTextAreaElement>(null);
  const current=navigation.find(n=>n[0]===tab);
  const editable=e.loaded&&!e.locked&&!e.busy;
  const valid=result?.version===e.editVersion.current;
  useEffect(()=>()=>parser.current?.terminate(),[]);
  useEffect(()=>{const changed=()=>{if(location.hash==='#models')setTab('models');};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
  function changeText(text:string){if(bytes(text)>262144){e.setError('Markdown 超过 256 KiB，未替换当前输入');return;}parser.current?.terminate();setParsing(false);setResult(null);setAck(false);e.changeMarkdown(text);}
  function parse(){
    parser.current?.terminate();setMessage('');setAck(false);setResult(null);setParsing(true);e.setError('');
    const worker=new Worker(new URL('./parse-worker.ts',import.meta.url),{type:'module'});parser.current=worker;const version=e.editVersion.current;
    worker.onmessage=event=>{worker.terminate();if(parser.current!==worker)return;parser.current=null;setParsing(false);if(event.data.ok)setResult({data:event.data.result,version});else e.setError(event.data.error);};
    worker.onerror=()=>{worker.terminate();setParsing(false);e.setError('解析器启动失败，请重新加载插件');};worker.postMessage({text:e.markdown});
  }
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage('已复制到剪贴板');}catch{e.setError('无法访问剪贴板，请展开提示词后手动复制，或下载文本');}}
  async function readMarkdown(file:File){try{if(file.size>262144)throw new Error('Markdown 文件超过 256 KiB');changeText(new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()));}catch{e.setError('无法导入：请使用不超过 256 KiB 的 UTF-8 Markdown 文件');}}
  async function readBackup(file:File){try{if(file.size>8388608)throw new Error('备份超过 8 MiB');const parsed=parseBackup(await file.text());if('format'in parsed){if(parsed.format==='resume-companion-editor-draft')setPendingDraft(parsed);else{setBackup(parsed);setSnapshot(parsed.state.current?'current':'previous');}}else setPending({...parsed,supplemental_fields:e.profile.supplemental_fields});}catch(err){e.setError((err as Error).message);}}
  async function exportBackup(){try{await e.flush();downloadFile('简历随行完整备份.json',await action('PROFILE_EXPORT'));setMessage('完整备份已导出，不包含模型 Key');}catch(err){e.setError((err as Error).message);}}
  function exportDraft(){downloadFile('简历随行本页草稿.json',{format:'resume-companion-editor-draft',version:1,profile:e.profile,markdown:e.markdown,fieldMetadata:e.metadata,sourceDocument:e.source});}
  function addCommon(key:string,label:string,description:string){if(e.profile.supplemental_fields.some(f=>f.field_key===key))return;const record=newRecord('supplemental_fields');e.changeProfile({...e.profile,supplemental_fields:[...e.profile.supplemental_fields,{...record,field_key:key,label,description}]});}
  const activeVersion=e.state?.versions.find(v=>v.id===e.state?.activeVersionId);
  const manageVersions=editable&&!e.dirty&&!versionBusy;
  async function versionAction(type:string,payload:Record<string,unknown>={}){setVersionBusy(true);e.setError('');try{await action(type,{...payload,expectedRevision:e.state?.revision});await e.load();setVersionDialog(null);}catch(err){e.setError((err as Error).message);}finally{setVersionBusy(false);}}
  function versionModal(mode:'new'|'copy'|'rename'|'delete'){setVersionDialog(mode);setVersionName(mode==='rename'?activeVersion?.name??'':mode==='copy'?`${activeVersion?.name??'简历'} 副本`:`简历版本 ${(e.state?.versions.length??0)+1}`);}
  const target=backup?(snapshot==='current'?backup.state.current:backup.state.previous):null;
  const candidate=result?{...result.data.candidate,supplemental_fields:e.profile.supplemental_fields}:null;
  return <div className="workspace"><aside className="sidebar"><Brand/><div className="nav-caption">我的简历</div><nav>{navigation.map(([key,num,title])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><span>{num}</span>{title}{key!=='basic'&&<small>{e.profile[key].length}</small>}</button>)}{extra.map(([key,title])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{title}</button>)}<button onClick={()=>openJournal()}>投递记录与统计 ↗</button></nav><div className="local-note">资料保存在当前浏览器<p>完整备份可带到另一台电脑。</p></div><button className="sidebar-link" disabled={!editable} onClick={()=>setPending({...demoProfile(),supplemental_fields:e.profile.supplemental_fields})}>用示例资料体验 ↗</button></aside>
    <main className="editor"><header className="editor-top"><div><span className="eyebrow">MY PROFILE / 我的资料</span><p className="save-state">{e.dirty?'有尚未保存的修改':e.state?.current?'正式资料已保存':'从一份属于你的简历开始'}{e.draftStatus&&` · ${e.draftStatus}`}</p></div><button className="primary" disabled={!editable||parsing} onClick={()=>{setMessage('');void e.save();}}>{e.busy?'保存中…':'保存资料'} <span aria-hidden="true">↗</span></button></header>
      <div className="page-title"><span className="eyebrow">RESUME COMPANION / 本地资料</span><h1>{current?.[2]??extra.find(t=>t[0]===tab)?.[1]}<span className="title-dot">.</span></h1><p>{current?.[3]??(tab==='import'?'把 AI 整理的 Markdown 变成可编辑资料。':tab==='models'?'配置你选择的提供商，辅助识别陌生网页字段。':'备份当前浏览器的资料，或核对并恢复历史版本。')}</p></div>
      {!inExtension&&<Notice>这是界面预览。请在 Chrome 中加载插件后使用保存和模型功能。</Notice>}
      {e.error&&<Notice error>{e.error}</Notice>}{e.status&&<Notice>{e.status}</Notice>}{message&&<Notice>{message}</Notice>}
      {tab!=='models'&&<section className="version-strip"><label className="form-field"><span>当前编辑的简历版本</span><select aria-label="编辑的简历版本" disabled={!manageVersions} value={e.state?.activeVersionId??''} onChange={event=>void versionAction('VERSION_SELECT',{id:event.target.value})}><option value="" disabled>尚未创建版本</option>{e.state?.versions.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><div className="toolbar"><button disabled={!manageVersions} onClick={()=>versionModal('new')}>新建空白版本</button><button disabled={!manageVersions||!activeVersion} onClick={()=>versionModal('copy')}>复制为新版本</button><button disabled={!manageVersions||!activeVersion} onClick={()=>versionModal('rename')}>重命名</button><button disabled={!manageVersions||!activeVersion} onClick={()=>versionModal('delete')}>删除版本</button></div>{e.dirty&&<p className="subtle">先保存资料，再切换或管理版本。每个版本保留自己的简历与补充资料。</p>}</section>}
      {e.locked&&<section className="card"><h2>检测到一份编辑草稿</h2><p>可能来自上次关闭的页面或另一窗口。恢复后，本窗口接管编辑；当前本页修改可先导出。</p><div className="toolbar"><button disabled={e.busy} onClick={()=>{if(e.state?.draft?.baseRevision!==e.state?.revision)setConfirm('draft');else void e.restoreDraft();}}>恢复草稿并接管</button><button onClick={exportDraft}>导出本页草稿</button><button onClick={()=>setConfirm('discard')}>放弃已存草稿，载入正式资料</button></div></section>}
      {!e.state?.current&&!e.dirty&&tab==='basic'&&<section className="card empty-start"><h2>先整理一份自己的资料</h2><p>从 AI 导入，或直接在下面手动填写。</p><div className="toolbar"><button className="primary" onClick={()=>setTab('import')}>从 AI 导入</button><button disabled={!editable} onClick={()=>setPending({...demoProfile(),supplemental_fields:e.profile.supplemental_fields})}>载入示例资料</button></div></section>}
      {tab==='models'?<ModelSettings/>:tab==='import'?<>
        <section className="card"><h2>1. 在你常用的 AI 中整理简历</h2><p className="muted">复制提示词，在 AI 中上传 PDF 或粘贴简历原文，再把得到的 Markdown 放到下面。</p><div className="toolbar"><button onClick={()=>void copy(AI_PROMPT)}>复制解析提示词</button><button onClick={()=>downloadFile('简历整理提示词.txt',AI_PROMPT,'text/plain')}>下载提示词</button><button disabled={!editable} onClick={()=>changeText(EMPTY_MARKDOWN)}>载入空模板</button></div><details><summary>查看完整提示词和模板</summary><pre className="text-preview">{AI_PROMPT}</pre></details></section>
        <section className="card"><h2>2. 粘贴并检查 Markdown</h2><div className="toolbar"><label className="file-button">导入 Markdown 文件<input type="file" accept=".md,.markdown,text/markdown" disabled={!editable} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void readMarkdown(file);}}/></label><button disabled={!editable} onClick={()=>changeText(exportMarkdown(e.profile,e.metadata,e.source))}>编辑当前资料 Markdown</button>{e.source&&<button disabled={!editable} onClick={()=>changeText(e.source!.text)}>载入历史导入原文</button>}</div>
          {e.source&&<p className="subtle">历史原文导入于 {new Date(e.source.importedAt).toLocaleString('zh-CN')}，对应修订 {e.source.profileRevision||'待保存'}；后续表单修改不会自动改写原文。</p>}
          <textarea ref={input} aria-label="Markdown 简历" className="markdown-input" disabled={!editable} value={e.markdown} onChange={event=>changeText(event.target.value)} spellCheck={false}/>
          <div className="toolbar"><button className="primary" disabled={!editable||!e.markdown.trim()||parsing} onClick={parse}>{parsing?'解析中…':'解析并预览'}</button>{parsing&&<button onClick={()=>{parser.current?.terminate();parser.current=null;setParsing(false);}}>取消解析</button>}<small>{bytes(e.markdown)} / 262144 字节</small></div>
        </section>
        {result&&candidate&&<section className="card"><h2>3. 核对差异后载入编辑区</h2><p>{describeImport(candidate)}</p><p className="subtle">更新简历内容，保留补充资料。载入编辑区后，点击“保存资料”才更新正式版本。</p>
          {!valid&&<Notice error>输入或资料已变化，请重新解析。</Notice>}
          {result.data.issues.slice(0,100).map((issue,i)=><div className={`import-issue ${issue.severity}`} key={i}><button onClick={()=>{const area=input.current;if(!area)return;const lines=e.markdown.split('\n');const start=lines.slice(0,issue.line-1).join('\n').length+(issue.line>1?1:0);area.focus();area.setSelectionRange(start,start+(lines[issue.line-1]?.length??0));}}>第 {issue.line} 行</button><span>{issue.message}</span></div>)}
          {result.data.issues.length>100&&<p>先显示前 100 处问题（共 {result.data.issues.length} 处），修正后重新解析。</p>}{result.data.issues.length>0&&<button onClick={()=>void copy('请按原提示词重新输出完整 resume-md/1 Markdown，保留原简历事实，不补造缺失信息。请修正以下问题：\n'+result.data.issues.map(i=>`第${i.line}行：${i.message}`).join('\n'))}>复制修正格式说明</button>}
          <Diff before={e.profile} after={candidate}/>
          {result.data.issues.some(i=>i.severity==='warning')&&<label className="check-line"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/>已核对提示；无法识别的原文保留，暂不用于填写</label>}
          <button className="primary" disabled={!editable||!valid||result.data.issues.some(i=>i.severity==='error')||(result.data.issues.some(i=>i.severity==='warning')&&!ack)} onClick={()=>{e.applyProfile(candidate,result.data.fieldMetadata,result.data.sourceDocument);setResult(null);setTab('basic');setMessage('已载入编辑区，请核对后保存');}}>应用到编辑区</button>
        </section>}
      </>:tab==='backup'?<>
        <section className="card"><h2>网页悬浮入口</h2><label className="check-line"><input type="checkbox" checked={e.state?.preferences.floatingEnabled??true} disabled={!e.loaded} onChange={async event=>{try{await action('PREFS_SET',{floatingEnabled:event.target.checked});await e.load();}catch(err){e.setError((err as Error).message);}}}/>在招聘和简历页面自动显示右下角悬浮球</label><p className="subtle">插件在普通网页中识别招聘表单。点击悬浮球，选择本次简历版本并核对填写内容。</p></section><section className="card"><h2>Codex 本地桥接</h2><label className="check-line"><input type="checkbox" checked={e.state?.preferences.codexBridgeEnabled??false} disabled={!e.loaded} onChange={async event=>{try{await action('PREFS_SET',{codexBridgeEnabled:event.target.checked});await e.load();}catch(err){e.setError((err as Error).message);}}}/>允许本机 Codex 枚举标签页并通过 DOM 扫描、填写和撤销</label><p className="subtle">默认关闭。支持选中的多个标签页，只开放扫描、填写、验证和撤销；不提供提交、下一步或上传能力。不使用时可关闭。</p></section><section className="card"><h2>完整备份</h2><p className="muted">包含正式资料、补充表、原文、草稿和上一份。模型 Key 不进入备份。</p><div className="toolbar"><button className="primary" onClick={exportBackup} disabled={!e.loaded||e.busy}>导出完整备份</button><label className="file-button">导入备份<input type="file" accept=".json,application/json" disabled={!editable} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void readBackup(file);}}/></label><button onClick={exportDraft}>导出本页草稿</button></div></section>
        <section className="card"><h2>导出简历文字</h2><p className="muted">按正式资料生成 Markdown，包含保留的原文补充信息；手工补充资料表通过完整备份迁移。</p><div className="toolbar"><button disabled={!e.state?.current} onClick={()=>{const s=e.state!.current!;downloadFile('我的简历.md',exportMarkdown(s.profile,s.fieldMetadata,s.sourceDocument),'text/markdown');}}>导出当前简历 Markdown</button><button disabled={!e.source} onClick={()=>downloadFile('上次导入原文.md',e.source!.text,'text/markdown')}>导出导入原文</button></div></section>
        <section className="card"><h2>恢复与清除</h2><p className="muted">卸载插件前请导出完整备份。恢复会生成新修订，并保留恢复前的正式资料。</p><div className="toolbar"><button disabled={e.busy||e.locked} onClick={()=>setConfirm('restore')}>恢复上一份备份</button><button className="danger-text" disabled={!editable} onClick={()=>setConfirm('clear')}>清除本地资料</button><button onClick={async()=>{try{downloadFile('简历原始数据.json',await action('PROFILE_EXPORT_RAW'));}catch(err){e.setError((err as Error).message);}}}>导出原始数据</button></div></section>
      </>:<>
        {tab==='supplemental_fields'&&<section className="card"><h2>添加常用空白资料</h2><div className="toolbar">{[['native_place','籍贯','与现居地、户籍和生源地分别维护'],['household','户籍所在地','用户确认的户口登记地'],['student_origin','生源地','按申请要求确认的生源地区'],['preferred_city','期望工作地点','希望工作的地点，不是现居城市'],['language','语言成绩说明','考试名称、成绩及时间'],['availability','到岗时间说明','用户确认的到岗安排']].map(([key,label,description])=><button key={key} disabled={!editable||e.profile.supplemental_fields.some(f=>f.field_key===`supplemental.${key}`)} onClick={()=>addCommon(`supplemental.${key}`,label,description)}>＋ {label}</button>)}</div></section>}
        <ProfileFields profile={e.profile} onChange={e.changeProfile} tab={tab} disabled={!editable}/>
        {Object.keys(e.metadata).length>0&&<details className="card"><summary>查看保留的日期原文与精度</summary>{Object.entries(e.metadata).map(([key,value])=><p key={key}>{value.raw} · {value.precision==='year'?'仅年份，填写年月前需补充月份':value.precision==='day'?'保留完整日期，当前按年月填写':'年月'} <button disabled={!editable} onClick={()=>{const p=structuredClone(e.profile);for(const rec of [...p.education,...p.experience,...p.projects,...p.certificates])if(key.startsWith(rec.id+'.')){const field=key.slice(rec.id.length+1);(rec as Record<string,unknown>)[field]=null;}const m={...e.metadata};delete m[key];e.applyProfile(p,m,e.source);}}>清除此日期</button></p>)}</details>}
      </>}
      <footer className="editor-footer"><span>简历随行 · 0.5.0 · 本地保存</span><button onClick={()=>setTab('backup')}>备份与恢复</button></footer>
    </main>
    {versionDialog&&<Modal title={versionDialog==='delete'?'删除这个简历版本？':versionDialog==='rename'?'重命名简历版本':versionDialog==='copy'?'复制为新简历版本':'新建简历版本'} onClose={()=>setVersionDialog(null)}>{versionDialog==='delete'?<p>删除“{activeVersion?.name}”及这个版本的上一份资料。投递记录保留，其他简历版本不受影响。</p>:<label className="form-field"><span>版本名称</span><input aria-label="版本名称" value={versionName} maxLength={80} onChange={event=>setVersionName(event.target.value)}/></label>}<div className="modal-actions"><button onClick={()=>setVersionDialog(null)}>取消</button><button className="primary" disabled={versionBusy} onClick={()=>void versionAction(versionDialog==='delete'?'VERSION_DELETE':versionDialog==='rename'?'VERSION_RENAME':'VERSION_CREATE',{id:e.state?.activeVersionId,name:versionName,clone:versionDialog==='copy'})}>确认{versionDialog==='delete'?'删除版本':versionDialog==='rename'?'重命名':'创建版本'}</button></div></Modal>}
    {pendingDraft&&<Modal title="导入编辑草稿" onClose={()=>setPendingDraft(null)}><p>替换本页简历、补充资料和 Markdown 编辑内容，正式资料在点击保存前不会改变。</p><Diff before={e.profile} after={pendingDraft.profile}/><div className="modal-actions"><button onClick={()=>setPendingDraft(null)}>取消</button><button className="primary" onClick={()=>{e.applyDraft(pendingDraft.profile,pendingDraft.markdown,pendingDraft.fieldMetadata,pendingDraft.sourceDocument);setPendingDraft(null);setTab('basic');}}>载入草稿到编辑区</button></div></Modal>}
    {pending&&<Modal title="检查即将替换的资料" onClose={()=>setPending(null)}><p>{describeImport(pending)}</p><Diff before={e.profile} after={pending}/><p>简历部分载入编辑区，补充资料保留。点击“保存资料”后才正式生效。</p><div className="modal-actions"><button onClick={()=>setPending(null)}>取消</button><button className="primary" onClick={()=>{e.applyProfile(pending);setPending(null);setMessage('已载入编辑区，请核对后保存');}}>替换编辑内容</button></div></Modal>}
    {backup&&<Modal title="检查完整备份恢复范围" onClose={()=>setBackup(null)}><p>备份含 {backup.state.versions.length||1} 个简历版本、{backup.state.applicationJournal.length} 条投递记录，将替换当前 {e.state?.applicationJournal.length??0} 条。恢复正式资料、补充资料、草稿和投递记录。当前正式资料将保留为上一份；模型 Key 不会导入。</p><details><summary>备份中的简历版本</summary>{backup.state.versions.map(v=><p key={v.id}>{v.name} · {v.current.profile.basic.full_name||'未填姓名'}</p>)}</details><label className="form-field"><span>选择备份中的版本</span><select value={snapshot} onChange={event=>setSnapshot(event.target.value as 'current'|'previous')}><option value="current" disabled={!backup.state.current}>正式版</option><option value="previous" disabled={!backup.state.previous}>上一份</option></select></label>{target&&<Diff before={e.profile} after={target.profile}/>}<div className="modal-actions"><button onClick={()=>setBackup(null)}>取消</button><button className="primary" disabled={!target||e.busy} onClick={async()=>{await e.mutate('BACKUP_RESTORE',{backup,snapshot});setBackup(null);}}>确认恢复完整备份</button></div></Modal>}
    {confirm&&<Modal title={confirm==='clear'?'清除本地资料？':confirm==='restore'?'恢复上一份备份？':confirm==='draft'?'核对旧草稿与最新资料':'放弃已保存草稿？'} onClose={()=>setConfirm(null)}>
      <p>{confirm==='clear'?'将清除正式所有版本的简历、补充资料、原文、草稿、上一份和投递记录；已导出的文件不受影响。模型 Key 请在模型设置中单独清除。':confirm==='restore'?'用上一份完整资料恢复，当前未保存修改将被替换。':confirm==='draft'?'正式资料在草稿创建后发生过变化。请核对差异，确认以这份草稿继续编辑。':'将放弃当前存储中的编辑草稿，包括其他窗口未正式保存的内容；可先取消并导出。'}</p>
      {confirm==='draft'&&e.state?.draft&&<Diff before={e.state.current?.profile??emptyProfile()} after={e.state.draft.profile}/>}
      <div className="modal-actions"><button onClick={()=>setConfirm(null)}>取消</button><button className="primary" disabled={e.busy} onClick={async()=>{if(confirm==='draft')await e.restoreDraft(true);else if(confirm==='discard')await e.discardDraft();else await e.mutate(confirm==='clear'?'PROFILE_CLEAR':'PROFILE_RESTORE');setConfirm(null);}}>确认{confirm==='clear'?'清除':confirm==='restore'?'恢复':confirm==='draft'?'差异并恢复':'放弃草稿'}</button></div>
    </Modal>}
  </div>;
}
function Diff({before,after}:{before:Profile;after:Profile}){const diff=importDiff(before,after),[limit,setLimit]=useState(100);return <div className="diff-list">{diff.length?diff.slice(0,limit).map(d=><div key={d.key}><small>{d.key}</small><p><del>{d.before}</del><span aria-hidden="true">→</span><strong>{d.after}</strong></p></div>):<p>资料内容一致</p>}{diff.length>limit&&<button onClick={()=>setLimit(limit+100)}>显示更多差异（还有 {diff.length-limit} 项）</button>}</div>;}
createRoot(document.getElementById('root')!).render(<App/>);
