export const cases = [
  {
    id: 'M02',
    tool: 'form_select_option',
    field: '折叠多选',
    args: { values: ['SQL'] },
    blocked: true,
    families: ['ant4', 'ant5'],
    unchanged: { 折叠多选: ['TypeScript', 'Python'] },
  },
  {
    id: 'M01',
    tool: 'form_select_option',
    field: '多选技能',
    args: { values: ['TypeScript', 'Python'] },
    expected: ['TypeScript', 'Python'],
  },
  {
    id: 'R01',
    tool: 'form_set_date',
    field: '经历范围',
    args: { range: { start: '2024-06-15', end: '2024-08-20' } },
    expected: ['2024-06-15', '2024-08-20'],
  },
  {
    id: 'R03',
    tool: 'form_set_date',
    field: '工作开始',
    args: {
      range: { start: '2024-06', current: true },
      end_field: '工作结束',
      current_field: '工作至今',
    },
    expected: '2024-06',
    extraExpected: { 工作至今: true, 工作结束: '' },
  },
  {
    id: 'D01',
    tool: 'form_set_date',
    field: '输入日期',
    value: '2024-06-15',
    expected: '2024-06-15',
  },
  {
    id: 'D02',
    tool: 'form_set_date',
    field: '只读日期',
    value: '2024-06-15',
    expected: '2024-06-15',
  },
  { id: 'D03', tool: 'form_set_date', field: '入学月份', value: '2024-06', expected: '2024-06' },
  {
    id: 'D04',
    tool: 'form_set_date',
    field: '确认日期',
    value: '2024-06-15',
    expected: '2024-06-15',
    families: ['ant5'],
  },
  {
    id: 'D05',
    tool: 'form_set_date',
    field: '格式日期',
    value: '2024-06-15',
    expected: '2024-06-15',
  },
  {
    id: 'D06',
    tool: 'form_set_date',
    field: '回滚日期',
    value: '2024-06-15',
    overwrite: true,
    blocked: true,
    families: ['ant4', 'ant5'],
  },
  {
    id: 'D07',
    tool: 'form_set_date',
    field: '只读日期',
    value: '2000-01-02',
    expected: '2000-01-02',
  },
  { id: 'D08', tool: 'form_set_date', field: '禁用日期', value: '2024-06-15', blocked: true },
  { id: 'D09', tool: 'form_set_date', field: '限制日期', value: '2010-06-15', blocked: true },
  {
    id: 'C01',
    tool: 'form_select_path',
    field: '两层地址',
    path: ['省乙', '同名区'],
    expected: ['b', 'bb'],
  },
  {
    id: 'C02',
    tool: 'form_select_path',
    field: '三层地址',
    path: ['北京市', '市辖区', '海淀区'],
    expected: ['north', 'city', 'district'],
  },
  {
    id: 'C04',
    tool: 'form_select_path',
    field: '异步地址',
    path: ['浙江省', '杭州市'],
    expected: ['p', 'hz'],
    delay: 800,
  },
  {
    id: 'C05',
    tool: 'form_select_path',
    field: '悬停地址',
    path: ['北京市', '市辖区', '海淀区'],
    expected: ['north', 'city', 'district'],
  },
  { id: 'C07', tool: 'form_select_path', field: '父级地址', path: ['北京市'], expected: ['north'] },
  {
    id: 'C08',
    tool: 'form_select_path',
    field: '叶子回显',
    path: ['北京市', '市辖区', '海淀区'],
    expected: ['north', 'city', 'district'],
  },
  { id: 'V01', tool: 'form_select_option', field: '虚拟选项', value: '候选175', expected: '175' },
];
